print("XXXXX")
print("X   X")
print("X   X")
print("X   X")
print("XXXXX")

print("ALUNO(A)     NOTA")
print("=========    ===== ")
print("ALINE        9.0")
print("MÁRIO        DEZ")
print("SÉRGIO       4.5")
print("SHIRLEY      7.0")

print("       x ")
print("      xxx")
print("     xxxxx")
print("    xxxxxxx")
print("   xxxxxxxxx")
print("  xxxxxxxxxxx")
print(" xxxxxxxxxxxxx")
print("xxxxxxxxxxxxxxx")
print("       xx")
print("       xx")
print("      xxxx")
